/* Generated by Amaranth Yosys 0.25 (PyPI ver 0.25.0.0.post77, git sha1 e02b7f64b) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(b, o, a);
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:27" *)
  wire [8:0] \$1 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:21" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:22" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:23" *)
  output [8:0] o;
  wire [8:0] o;
  assign \$1  = a + (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:27" *) b;
  assign o = \$1 ;
endmodule
