/* Generated by Amaranth Yosys 0.25 (PyPI ver 0.25.0.0.post77, git sha1 e02b7f64b) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(b, o, a);
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:39" *)
  wire [7:0] \$1 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:41" *)
  wire \$10 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:39" *)
  wire [6:0] \$2 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:39" *)
  wire \$4 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:39" *)
  wire [7:0] \$6 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:40" *)
  wire \$8 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:33" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:34" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:35" *)
  output [8:0] o;
  wire [8:0] o;
  assign \$10  = a[1] | (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:41" *) b[1];
  assign \$2  = a[7:2] + (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:39" *) b[7:2];
  assign \$4  = a[1] & (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:39" *) b[1];
  assign \$6  = \$2  + (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:39" *) \$4 ;
  assign \$8  = a[0] | (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:40" *) b[0];
  assign \$1  = \$6 ;
  assign o[1] = \$10 ;
  assign o[0] = \$8 ;
  assign o[8:2] = \$6 [6:0];
endmodule
