/* Generated by Amaranth Yosys 0.25 (PyPI ver 0.25.0.0.post77, git sha1 e02b7f64b) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(b, o, a);
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:52" *)
  wire [6:0] \$1 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:54" *)
  wire \$10 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:55" *)
  wire \$12 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:52" *)
  wire [5:0] \$2 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:52" *)
  wire \$4 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:52" *)
  wire [6:0] \$6 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:53" *)
  wire \$8 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:46" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:47" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:48" *)
  output [8:0] o;
  wire [8:0] o;
  assign \$10  = a[1] | (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:54" *) b[1];
  assign \$12  = a[2] | (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:55" *) b[2];
  assign \$2  = a[7:3] + (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:52" *) b[7:3];
  assign \$4  = a[2] & (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:52" *) b[2];
  assign \$6  = \$2  + (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:52" *) \$4 ;
  assign \$8  = a[0] | (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:53" *) b[0];
  assign \$1  = \$6 ;
  assign o[2] = \$12 ;
  assign o[1] = \$10 ;
  assign o[0] = \$8 ;
  assign o[8:3] = \$6 [5:0];
endmodule
