/* Generated by Amaranth Yosys 0.25 (PyPI ver 0.25.0.0.post77, git sha1 e02b7f64b) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(b, o, a);
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:12" *)
  wire [8:0] \$1 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:12" *)
  wire [7:0] \$2 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:12" *)
  wire \$4 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:12" *)
  wire [8:0] \$6 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:13" *)
  wire \$8 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:6" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:7" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:8" *)
  output [8:0] o;
  wire [8:0] o;
  assign \$2  = a[7:1] + (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:12" *) b[7:1];
  assign \$4  = a[0] & (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:12" *) b[0];
  assign \$6  = \$2  + (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:12" *) \$4 ;
  assign \$8  = a[0] | (* src = "/home/simuse/Desktop/Amaranth/test/adder.py:13" *) b[0];
  assign \$1  = \$6 ;
  assign o[0] = \$8 ;
  assign o[8:1] = \$6 [7:0];
endmodule
