/* Generated by Amaranth Yosys 0.25 (PyPI ver 0.25.0.0.post78, git sha1 e02b7f64b) */

(* \amaranth.hierarchy  = "top.adder1" *)
(* generator = "Amaranth" *)
module adder1(o1, a1, a2);
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder1.py:15" *)
  wire [31:0] \$1 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder1.py:15" *)
  wire [31:0] \$2 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:14" *)
  input [31:0] a1;
  wire [31:0] a1;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:15" *)
  input [31:0] a2;
  wire [31:0] a2;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:23" *)
  output [31:0] o1;
  wire [31:0] o1;
  assign \$2  = a1[31:1] + (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder1.py:15" *) a2[31:1];
  assign \$1  = \$2 ;
  assign o1[31:1] = \$2 [30:0];
  assign o1[0] = a2[0];
endmodule

(* \amaranth.hierarchy  = "top.adder2" *)
(* generator = "Amaranth" *)
module adder2(o2, a3, a4);
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder2.py:13" *)
  wire [32:0] \$1 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder2.py:13" *)
  wire [32:0] \$2 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:16" *)
  input [31:0] a3;
  wire [31:0] a3;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:17" *)
  input [31:0] a4;
  wire [31:0] a4;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:24" *)
  output [31:0] o2;
  wire [31:0] o2;
  assign \$2  = a3 + (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder2.py:13" *) a4;
  assign \$1  = \$2 ;
  assign o2 = \$2 [31:0];
endmodule

(* \amaranth.hierarchy  = "top.adder3" *)
(* generator = "Amaranth" *)
module adder3(a6, o3, a5);
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder3.py:13" *)
  wire [32:0] \$1 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder3.py:13" *)
  wire [32:0] \$2 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:18" *)
  input [31:0] a5;
  wire [31:0] a5;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:19" *)
  input [31:0] a6;
  wire [31:0] a6;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:25" *)
  output [31:0] o3;
  wire [31:0] o3;
  assign \$2  = a5 + (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder3.py:13" *) a6;
  assign \$1  = \$2 ;
  assign o3 = \$2 [31:0];
endmodule

(* \amaranth.hierarchy  = "top.adder4" *)
(* generator = "Amaranth" *)
module adder4(o4, a7, a8);
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder4.py:13" *)
  wire [32:0] \$1 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder4.py:13" *)
  wire [32:0] \$2 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:20" *)
  input [31:0] a7;
  wire [31:0] a7;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:21" *)
  input [31:0] a8;
  wire [31:0] a8;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:26" *)
  output [31:0] o4;
  wire [31:0] o4;
  assign \$2  = a7 + (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder4.py:13" *) a8;
  assign \$1  = \$2 ;
  assign o4 = \$2 [31:0];
endmodule

(* \amaranth.hierarchy  = "top.adder5" *)
(* generator = "Amaranth" *)
module adder5(o2, o5, o1);
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder5.py:13" *)
  wire [32:0] \$1 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder5.py:13" *)
  wire [32:0] \$2 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:23" *)
  input [31:0] o1;
  wire [31:0] o1;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:24" *)
  input [31:0] o2;
  wire [31:0] o2;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:27" *)
  output [31:0] o5;
  wire [31:0] o5;
  assign \$2  = o1 + (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder5.py:13" *) o2;
  assign \$1  = \$2 ;
  assign o5 = \$2 [31:0];
endmodule

(* \amaranth.hierarchy  = "top.adder6" *)
(* generator = "Amaranth" *)
module adder6(o4, o6, o3);
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder6.py:13" *)
  wire [32:0] \$1 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder6.py:13" *)
  wire [32:0] \$2 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:25" *)
  input [31:0] o3;
  wire [31:0] o3;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:26" *)
  input [31:0] o4;
  wire [31:0] o4;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:28" *)
  output [31:0] o6;
  wire [31:0] o6;
  assign \$2  = o3 + (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder6.py:13" *) o4;
  assign \$1  = \$2 ;
  assign o6 = \$2 [31:0];
endmodule

(* \amaranth.hierarchy  = "top.adder7" *)
(* generator = "Amaranth" *)
module adder7(o6, o7, o5);
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder7.py:13" *)
  wire [32:0] \$1 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder7.py:13" *)
  wire [32:0] \$2 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:27" *)
  input [31:0] o5;
  wire [31:0] o5;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:28" *)
  input [31:0] o6;
  wire [31:0] o6;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:29" *)
  output [31:0] o7;
  wire [31:0] o7;
  assign \$2  = o5 + (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder7.py:13" *) o6;
  assign \$1  = \$2 ;
  assign o7 = \$2 [31:0];
endmodule

(* \amaranth.hierarchy  = "top.adder8" *)
(* generator = "Amaranth" *)
module adder8(o7, a9, o8);
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder8.py:13" *)
  wire [32:0] \$1 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder8.py:13" *)
  wire [32:0] \$2 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:22" *)
  input [31:0] a9;
  wire [31:0] a9;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:29" *)
  input [31:0] o7;
  wire [31:0] o7;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:30" *)
  output [31:0] o8;
  wire [31:0] o8;
  assign \$2  = o7 + (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/built_adder8.py:13" *) a9;
  assign \$1  = \$2 ;
  assign o8 = \$2 [31:0];
endmodule

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(a2, a3, a4, a5, a6, a7, a8, a9, o, a1);
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:41" *)
  wire [32:0] \$1 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:44" *)
  wire [32:0] \$10 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:44" *)
  wire [32:0] \$11 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:45" *)
  wire [32:0] \$13 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:45" *)
  wire [32:0] \$14 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:54" *)
  wire [31:0] \$16 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:41" *)
  wire [32:0] \$2 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:42" *)
  wire [32:0] \$4 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:42" *)
  wire [32:0] \$5 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:43" *)
  wire [34:0] \$7 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:43" *)
  wire [34:0] \$8 ;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:14" *)
  input [31:0] a1;
  wire [31:0] a1;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:15" *)
  output [31:0] a2;
  wire [31:0] a2;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:31" *)
  wire [31:0] a2p;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:16" *)
  input [31:0] a3;
  wire [31:0] a3;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:17" *)
  output [31:0] a4;
  wire [31:0] a4;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:32" *)
  wire [31:0] a4p;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:18" *)
  output [31:0] a5;
  wire [31:0] a5;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:33" *)
  wire [31:0] a5p;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:19" *)
  output [31:0] a6;
  wire [31:0] a6;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:34" *)
  wire [31:0] a6p;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:20" *)
  input [31:0] a7;
  wire [31:0] a7;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:21" *)
  output [31:0] a8;
  wire [31:0] a8;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:35" *)
  wire [31:0] a8p;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:22" *)
  input [31:0] a9;
  wire [31:0] a9;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:23" *)
  wire [31:0] adder1_o1;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:24" *)
  wire [31:0] adder2_o2;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:25" *)
  wire [31:0] adder3_o3;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:26" *)
  wire [31:0] adder4_o4;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:27" *)
  wire [31:0] adder5_o5;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:28" *)
  wire [31:0] adder6_o6;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:29" *)
  wire [31:0] adder7_o7;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:30" *)
  wire [31:0] adder8_o8;
  (* src = "/home/diesquivel@estudiantes.ie.tec.ac.cr/eda_proyecto/dut.py:13" *)
  output [31:0] o;
  wire [31:0] o;
  adder1 adder1 (
    .a1(a1),
    .a2(32'd0),
    .o1(adder1_o1)
  );
  adder2 adder2 (
    .a3(a3),
    .a4(32'd0),
    .o2(adder2_o2)
  );
  adder3 adder3 (
    .a5(32'd0),
    .a6(32'd0),
    .o3(adder3_o3)
  );
  adder4 adder4 (
    .a7(a7),
    .a8(32'd0),
    .o4(adder4_o4)
  );
  adder5 adder5 (
    .o1(adder1_o1),
    .o2(adder2_o2),
    .o5(adder5_o5)
  );
  adder6 adder6 (
    .o3(adder3_o3),
    .o4(adder4_o4),
    .o6(adder6_o6)
  );
  adder7 adder7 (
    .o5(adder5_o5),
    .o6(adder6_o6),
    .o7(adder7_o7)
  );
  adder8 adder8 (
    .a9(a9),
    .o7(adder7_o7),
    .o8(adder8_o8)
  );
  assign \$1  = \$2 ;
  assign \$4  = \$5 ;
  assign \$7  = \$8 ;
  assign \$10  = \$11 ;
  assign \$13  = \$14 ;
  assign a2p = 32'd0;
  assign a4p = 32'd0;
  assign a5p = 32'd0;
  assign a6p = 32'd0;
  assign a8p = 32'd0;
  assign o = \$16 ;
  assign a8 = \$14 [31:0];
  assign a6 = \$11 [31:0];
  assign a5 = \$8 [31:0];
  assign a4 = \$5 [31:0];
  assign a2 = \$2 [31:0];
  assign \$2  = 33'h000000000;
  assign \$5  = 33'h000000000;
  assign \$8  = 35'h000000000;
  assign \$11  = 33'h000000000;
  assign \$14  = 33'h000000000;
  assign \$16  = { 4'h0, adder8_o8[31:4] };
endmodule
