/* Generated by Amaranth Yosys 0.25 (PyPI ver 0.25.0.0.post77, git sha1 e02b7f64b) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(ovf, clk, rst, en);
  reg \$auto$verilog_backend.cc:2083:dump_module$2  = 0;
  (* src = "/home/simuse/Desktop/Amaranth/test/up_counter.py:59" *)
  wire \$1 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/up_counter.py:70" *)
  wire [16:0] \$3 ;
  (* src = "/home/simuse/Desktop/Amaranth/test/up_counter.py:70" *)
  wire [16:0] \$4 ;
  (* src = "/home/simuse/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/simuse/Desktop/Amaranth/test/up_counter.py:51" *)
  reg [15:0] count = 16'h0000;
  (* src = "/home/simuse/Desktop/Amaranth/test/up_counter.py:51" *)
  reg [15:0] \count$next ;
  (* src = "/home/simuse/Desktop/Amaranth/test/up_counter.py:44" *)
  input en;
  wire en;
  (* src = "/home/simuse/Desktop/Amaranth/test/up_counter.py:46" *)
  output ovf;
  wire ovf;
  (* src = "/home/simuse/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  assign \$1  = count == (* src = "/home/simuse/Desktop/Amaranth/test/up_counter.py:59" *) 5'h19;
  assign \$4  = count + (* src = "/home/simuse/Desktop/Amaranth/test/up_counter.py:70" *) 1'h1;
  always @(posedge clk)
    count <= \count$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \count$next  = count;
    (* src = "/home/simuse/Desktop/Amaranth/test/up_counter.py:62" *)
    casez (en)
      /* src = "/home/simuse/Desktop/Amaranth/test/up_counter.py:62" */
      1'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/simuse/Desktop/Amaranth/test/up_counter.py:64" *)
          casez (ovf)
            /* src = "/home/simuse/Desktop/Amaranth/test/up_counter.py:64" */
            1'h1:
                \count$next  = 16'h0000;
            /* src = "/home/simuse/Desktop/Amaranth/test/up_counter.py:68" */
            default:
                \count$next  = \$4 [15:0];
          endcase
    endcase
    (* src = "/home/simuse/.local/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \count$next  = 16'h0000;
    endcase
  end
  assign \$3  = \$4 ;
  assign ovf = \$1 ;
endmodule
